# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'JSPatchDemo' do
  # use_frameworks!

  # Pods for JSPatchDemo
  # pod 'KVOController', '~> 1.2.0'
  # pod 'ReactiveObjC', '~> 2.1.2'
  # pod 'ReactiveObjC', :git => 'https://github.com/doggy/ReactiveObjC', :commit => '6cfa511'
  pod 'ReactiveObjC', :git => 'https://github.com/ReactiveCocoa/ReactiveObjC', :branch => 'selector-signal-interop'
  pod 'JSPatch', '~> 1.1.3'
  pod 'IQKeyboardManager', '~> 4.0.8'

  target 'JSPatchDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JSPatchDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
